In [1]:
import pandas as pd 
import numpy as np
from collections import Counter
df = pd.read_csv("flower_business_merge.csv", encoding="utf-8", sep=",")
df

統一編號          營業人名稱      資本額 使用統一發票  \
0      94920851  保証責任南投縣和興合作農場   200000      N   
1      45651105           祥林園藝    90000      N   
2      80590886      松濤園企業有限公司  1200000      N   
3      14606346           百合園藝    50000      N   
4      39919339           中興蘭園   200000      N   
5      19258866   松柏林園藝綠化土木工程行     3000      N   
6      78121043          文通林業行   600000      Y   
7      10920667          尚宏山業行  6000000      N   
8      80088169       順瓏農產有限公司  5000000      Y   
9      62164967            統裕行  4700000      N   
10     42742309      美宥美企業有限公司  1000000      N   
11     53975780       宿山企業有限公司   500000      N   
12     28316254    一家國際生活館有限公司  1000000      N   
13     89981060     鎮峰園藝景觀有限公司  5000000      N   
14      9345048          太朴松濤園   200000      N   
15     39785205         台灣茗門茶業   100000      N   
16     14617131           福田花莊     3000      N   
17      9231707        竹山滿意清潔社    10000      N   
18     53498751       聖東種苗有限公司  8000000      N   
19     53794367         臣達有限公司   510000      N   
20     21824655          松柏園藝社   360000      N   
21     61949884          見生農藥行     3000      N   
22     21477331        如祥園藝工程行   200000      N   
23     47354622        煦虹綠化園藝行   200000      N   
24     22567818       隆詮企業有限公司  6000000      N   
25     28562229   介美麗花卉進出口有限公司  5000000      N   
26     38972840        築園造景園藝社   200000      N   
27     54507808       仟崧事業有限公司   600000      Y   
28     45547271        弘奇園藝清潔社   480000      N   
29     72428263          慶慶園藝行   200000      N   
...         ...            ...      ...    ...   
22025  19929458          西村花藝行     5000      N   
22026  18447334        二嫂花藝設計坊     3000      N   
22027  21308286          阿英花卉行    30000      N   
22028  13648902          長林鮮花苑     3000      N   
22029  92032599         貴蘭園藝花卉    30000      N   
22030  57926522          豆豆豆花店    50000      N   
22031  81862196           龍品商行   200000      N   
22032   7828053           和昌花園     3000      N   
22033  17365361        打狗傳統豆花店     3000      N   
22034  21333927          自然風園藝     3000      N   
22035  14571352          陸豐企業行   200000      N   
22036  20213311           東松花店    30000      N   
22037   7820926          楓情園藝坊    10000      N   
22038  78714539          愈豐鮮花店     3000      N   
22039  19227772         東興文具花坊    30000      N   
22040   6852358          日月鮮花店     5000      N   
22041  82103433          愛友企業社     3000      N   
22042   7827028          春菊鮮花店     5000      N   
22043  86664012     川敏國際股份有限公司  5000000      N   
22044  19218773           九九花坊    10000      N   
22045  25945814          愛上巴里島     3000      N   
22046  25907121          大欉園藝社   200000      N   
22047  36907540         家鈴養生農場    50000      N   
22048  21378326         北高雄水族館   300000      N   
22049  89422480       技俊企業有限公司  2000000      N   
22050  81866756          景山園藝行    10000      N   
22051  57974299          綠川園藝行    50000      N   
22052  14831499          創世咖啡館    10000      N   
22053  21389920    創世咖啡館美術館門市部        0      N   
22054  24660558         和景有限公司   200000      N   

                                  行業代碼_new  \
0      [453212 485112.0 472935.0 932999.0]   
1      [453212 711112.0 485113.0 485299.0]   
2      [453212 453211.0 711112.0 432000.0]   
3                                 [485111]   
4               [485111 485112.0 740999.0]   
5               [432000 432000.0 429099.0]   
6         [20011 20013.0 485112.0 11799.0]   
7                         [485112 20011.0]   
8      [453212 453113.0 485111.0 485112.0]   
9        [453212 813000.0 20011.0 11799.0]   
10                       [485111 969022.0]   
11               [11999 453213.0 472999.0]   
12     [472999 473999.0 476111.0 485111.0]   
13                                [711112]   
14      [782000 485112.0 472935.0 20011.0]   
15     [451099 472915.0 485112.0 472999.0]   
16                       [773099 485111.0]   
17     [812100 813000.0 474917.0 485111.0]   
18                                 [

In [2]:
c1 = df["組織別名稱"]
print(Counter(c1))

Counter({'0': 9308, '獨資': 8857, '有限公司': 2811, '股份有限公司': 570, '合夥': 213, '其他': 140, '本國公司設立之分公司': 123, '合作社': 22, '外國公司在台之分公司': 10, '無限公司': 1})


In [8]:
nraw = df.shape[0]
data_arr = np.array(df)
for i in range(10):
    strl = data_arr[i,4]
    print(strl)

[453212 485112.0 472935.0 932999.0]
[453212 711112.0 485113.0 485299.0]
[453212 453211.0 711112.0 432000.0]
[485111]
[485111 485112.0 740999.0]
[432000 432000.0 429099.0]
[20011 20013.0 485112.0 11799.0]
[485112 20011.0]
[453212 453113.0 485111.0 485112.0]
[453212 813000.0 20011.0 11799.0]
